title: Archimboldi
email: vonarchimboldi@protonmail.com
description: Archimboldi's website
url: "https://archimboldi.com"

baseurl: ""
permalink: /:categories/:title:output_ext
markdown: kramdown
plugins:
  - jekyll-feed
